In [9]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,66,3,4,5],[1,2,3,4,5]])
i=10
arr1
arr2

array([[ 1, 66,  3,  4,  5],
       [ 1,  2,  3,  4,  5]])

In [11]:
arr3=np.zeros((3,3))
arr3

TypeError: Cannot interpret '3' as a data type

In [12]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [17]:
arr7.astype('int')
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])